### ISSUE TITLE
Atomic improvement

### ISSUE THREAD

**Issue by Risa123** [TeamMonumental/FissionWarfare#1]
- buff the atomic bomb (too weak i think)
- add radioctivity effect

**Comment by Calemi** [comment]
That's funny, because we've been talking about buffing the atomic and that radioactive effect lately. The biggest and obvious problem is the performance. It took like 20 seconds to completely load in the explosion. Luckily we've found unused code in the explosions and removing it, made it run very smooth and fast. We are currently thinking about making the "radioactive effect" (its more like a block eating others) in a different explosive.

Anyways, thanks for the suggestion. It's always great to read these!
